### ISSUE TITLE
Missing columns in QX600 export

### ISSUE THREAD

**Issue by ppreshant** [ppreshant/WW-CoV2-project#65]
I am testing the pipeline for working with [QX600 data ](https://docs.google.com/spreadsheets/d/1jdO_P9SZGezSTLiIARtSmA7qaUuX3wA-jCe7YiQ1sCI/edit#gid=670879411) (plates: 853, 857, 858, and 859) but it is missing a few columns.
I started addressing a few in the branch `qx600_adaptation` : 250e9d73e9dfab3bf2810c846f43b9c0518a426d

Things to check @kmp11 
1. Is the data exported in the best way possible? explore other ways to export `.csv` which preserves `Target` names
2. Missing columns : 
- "CopiesPer20uLWell" - PK made this up by doing 20 x copies/ul so no issue
- `PoissonConfMax` and `Min` - These are not output to HHD, so let's make them optional in the code using `any_of()` function
- `Threshold` - ?
4. Main problem : column `Target` contains numbers 1-6 instead of the actual names of targets. It causes type to become numeric and also information on which target is at what position is lost.

for Prashant's reference : `Target` causing issue in line 62 at `left_join(., template_volume_ddpcr, by = 'Target')` in `1-processing..`

**Comment by kmp11** [comment]
Resolved. Mistakenly had the targets numbered 1-6 on the software instead of the actual target names.

**Comment by kmp11** [comment]
Plates 853, 857, 858, and 859 are all Qx-600 plates now with the properly labeled targets.

**Comment by kmp11** [comment]
R script still throwing error when running the 853 test plate though. "Can't subset columns that don't exist". Could be looking for another column that's missing in the Qx600 export format?

**Comment by ppreshant** [comment]
Ah, I see. Thank you for fixing the targets.

The missing column might be the `CopiesPer20uLWell` which i fixed in the
new branch. Have you tried the new branch that says `QX600`?

I'll take another look on Monday evening and let you know.

**Comment by kmp11** [comment]
Ah, didn't switch branches. Still getting an error after switching though. Just for getting a jump start on this tomorrow, as HHD will be wanting the flu/rsv data.
The error I got:
Error: Problem with `mutate()` column `PoissonConfMax_per_uL_RNA`.
i `PoissonConfMax_per_uL_RNA = PoissonConfMax * 20/template_vol`.
x object 'PoissonConfMax' not found

**Comment by ppreshant** [comment]
I see. The data doesn't have the posson confidence intervals. I will make those columns optional in the code now. When do you need to email HHD the data by? 

I'll try fixing these today, but we can loop in @Jingjing0110 to help after that?

**Comment by kmp11** [comment]
Yes, I've noticed it also doesn't have the "Threshold" column after more troubleshooting. Is the data from these columns important for the calculations?

**Comment by ppreshant** [comment]
I had these in the complete data output for troubleshooting purposes but they are not reported to HHD. I'm making these columns optional now, will give you and update once I'm done (hopefully 30 mins)

**Comment by ppreshant** [comment]
I made some changes to fix these `Poisson` and `Threshold` issues now and tested that it runs on `dd.WW853` data. Can you check on the other ones and confirm. I'll wait for this before merging into the main branch `WW_main`

Also I made a few other changes that the latest version of `dplyr  1.1.0` required. If you are facing any errors relating to function incompatibility then make sure to update your `dplyr` using `install.packages('dplyr')`

**Comment by kmp11** [comment]
Hmm still getting an error when writing to qpcr complete data, and it doesn't write to the final sheet for HHD. I tried updated the dplyr and tidyverse packages, but same error.

```Client specified an invalid argument. Check error message and error details for more information.
• Invalid value at 'requests[2].update_cells.rows[341].values[15].user_entered_value.number_value' (TYPE_DOUBLE), "-Inf"
Error details:
Field violations
* Field:
  requests[2].update_cells.rows[341].values[15].user_entered_value.number_value
  Description: Invalid value at
  'requests[2].update_cells.rows[341].values[15].user_entered_value.number_value'
  (TYPE_DOUBLE), "-Inf" ```

**Comment by kmp11** [comment]
Also, I was wondering if the new droplet volume would affect the results when running through the pipeline? Should we convert back to the qx-200 droplet volume for consistency, or stick with the updated version?

**Comment by ppreshant** [comment]
I made another issue for discussing the recalculations - Let's discuss on that thread #66 
I'm looking into the other errors now

**Comment by ppreshant** [comment]
That's an interesting error. Seems to be occurring due to the -Infinity values that might be arising from the missing the poisson confMax and Min values that I made filled up with missing numbers (NaNs). 

This is an error only in writing to google sheets, since the csv file is saved on my computer at `excel files/Complete data`
[030623 5plex PKtest.csv](https://github.com/ppreshant/WW-CoV2-project/files/11033680/030623.5plex.PKtest.csv)

**Comment by ppreshant** [comment]
I figured out that it does not write to google sheets if there are `infinity : Inf` or `-Inf` values in the data. I identified that one WICD # 47 had the target still as 6 which caused the limit of detection to be -Inf. fixing it should clean up the google sheet writing issue!
![image](https://user-images.githubusercontent.com/14856479/226749945-57d002d3-e0dd-4d8d-a8e5-2112274b6fab.png)

Try fixing this and let me know.

**Comment by kmp11** [comment]
That seemed to fix the issue for the 5-plex data. However, I wasn't able to run the regular duplex data on that branch at all. Even after switching back to master branch, it came up with this error below. It did fully run the plate and write correctly to the WWTP data sheet, but did not write the run log on the user inputs tab.

Error in `filter()`:
i In argument: `across(...)`.
Caused by error in `across()`:
! Can't compute column `WWTP`.
Caused by error in `fn()`:
! unused arguments (c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, NA, NA, NA, NA, NA, NA, NA, NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, NA, NA, NA, NA, NA, NA, NA, NA, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE

**Comment by ppreshant** [comment]
Holy cow! We should fix this today then.

This is definitely because of the updated `dplyr`. I fixed it in QX600 (commit : 78dc166d4adeae6210059c79e8e879d9a12e813f) so will be fixed when merged.

Which data did this come up with?

**Comment by kmp11** [comment]
This was from the regular WWTP plate from 03/20/23. Plate 862. Should already be the first tab on the user inputs sheet

**Comment by kmp11** [comment]
Also, I'm just noticing that the script terminates right after writing to the WWTP and manhole data for HHD sheet. So, it does not write to the qpcr complete data or any of the other sheets.
This issue will be present on any of the N1N2 only plates. I'll leave the plate 863 at the front for testing though.

**Comment by ppreshant** [comment]
I fixed a bug with the recent push to the QX_600 branch and `dd.WW862` runs now. I'll check the main branch in an hour. Till then check if this branch works for regular data analysis?

**Comment by ppreshant** [comment]
Since the regular branch is not working, I'll merge the QX600 which was working for 862 and the 5-plex ones you tested
